version: '2'
services:
    # APIServer_nginx
    c-nginx:
        build: "./nginx"
        image: "c-nginx"
        # restart: no
        ports:
            - "80:80"
        depends_on:
            - "c-uwsgi"

    # APIServer_uwsgi
    c-uwsgi:
        build: "./uwsgi"
        image: "c-uwsgi"
        # restart: no
        expose:
            - "3031"
        depends_on:
            - "c-mariadb"

    # APIServer_mariaDB
    c-mariadb:
        build: "./mariadb"
        image: "c-mariadb"
        environment:
            MYSQL_ROOT_PASSWORD: root
        # restart: no
        expose:
            - "3306"
